CFLAGS= -Wall -Os -O3 -std=gnu++11 -pedantic -I${HOME}/.local/include -L${HOME}/.local/lib -licuio -licui18n -licuuc -licudata -I${HOME}/.local/include/libxml2/libxml -L${HOME}/.local/lib -lxml2 -I${HOME}/.local/include/eigen3/ /usr/local/lib64/libarmadillo.so

all:
	g++ $(CFLAGS) mine_emails.cpp -o mine_emails 

debug:
	g++ $(CFLAGS) -g mine_emails.cpp -o mine_emails 

clean:
	rm mine_emails