CFLAGS= -Wall -Os -O3 -std=gnu++11 -pedantic -I${HOME}/.local/include  -I${HOME}/.local/include/libxml2 -I${HOME}/.local/include/eigen3  
LDLIBS= -licuio -licui18n -licuuc -licudata -lxml2 /opt/OpenBLAS/lib/libopenblas.so /usr/local/lib64/libarmadillo.so
LDFLAGS= -L${HOME}/.local/lib

all:
	g++ $(CFLAGS) mine_emails.cpp -o mine_emails $(LDFLAGS) $(LDLIBS)

debug:
	g++ -v -g $(CFLAGS) mine_emails.cpp -o mine_emails $(LDFLAGS) $(LDLIBS)

clean:
	rm mine_emails